apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q80s0bpp7-java-springboot 
  janus-idp.io/tekton: q80s0bpp7-java-springboot
  backstage.io/kubernetes-id: q80s0bpp7-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q80s0bpp7-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml